server:
  port: 9000

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect


db:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/temp_db?ApplicationName=testApp&stringtype=unspecified
    username: postgres
    password: postgres
    data-source-properties: stringtype=unspecified #allow the app to write to the db 'json' column
    pool-name: dbPool
    maximum-pool-size: 10
    max-life-time: 600000

app:
 kafka:
  bootstrap-servers: localhost:29092
  group-id: test111
  topics:
    topic-name: NewTopic
  producer:
    transaction-id-prefix: tx-
    idem-potence: true
  use-trust-store: false
  truststore:
    location: classpath:/strimzi-devtest-transrep-truststore.jks
    password: S
  keystore:
    location: classpath:/strimzi-super-user-keystore.jks
    password: S
  key:
    password: j




logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: trace